Abilities:
  Chi:
    FlyingKick:
      Enabled: true
      # Cooldown in milliseconds.
      Cooldown: 16000
      # Number of blocks per second.
      Description: "FlyingKick."
      Speed: 20.0
      # Maximum amount of time the movement state can last.
      Duration: 2000
      # How large the explosion at the end of the movement state is.
      # It should be pretty small because the particles are rendered in 3 waves.
      ExplosionRadius: 3.5
      # How long the caster has to hit the ground before the explosion is cancelled.
      GroundWaitTime: 1000
      # Amount of damage the explosion does. 1 damage = 0.5 hearts.
      Damage: 3
    Karma:
      Enabled: false
      # Cooldown in milliseconds.
      Cooldown: 40000
      Description: "Karma."
      # How many blocks away the target can be.
      Range: 30.0
      # How long Karma lasts with 0 combo points in milliseconsd.
      # If BaseDuration is higher than MaxDuration, Karma won't use any combo points and will default to BaseDuration.
      BaseDuration: 3000
      # How long Karma lasts with full combo points in milliseconds.
      MaxDuration: 6000
    KickPunch:
      Enabled: false
      # Cooldown in milliseconds.
      Cooldown: 1500
      Description: "Swing at a target to deal extra damage and gain combo points. This is one of the main ways to gain combo points."
      # Amount of damage done. 1 damage = 0.5 hearts.
      Damage: 2
      # The number of combo points to generate.
      ComboPointsGenerated: 2
    LegSweep:
      Enabled: false
      # Cooldown in milliseconds.
      Cooldown: 12000
      Description: "LegSweep."
      # How long the stun lasts in milliseconds.
      StunDuration: 1000
      # How long it takes to do a full sweep in milliseconds.
      SweepDuration: 500
      # The length of the sweep in blocks.
      SweepRadius: 3.0
    Ambush:
      Enabled: true
      # Cooldown in milliseconds.
      Cooldown: 25000
      Description: "Use sneak to vanish in a cloud of smoke. Stealth can only be activated while not being watched. Attack the target while stealthed to deal extra damage."
      # How much damage the attack from stealth deals. 1 damage = 0.5 hearts.
      Damage: 5.0
      # How long the invisibility lasts in milliseconds.
      StealthDuration: 8000
      # How many blocks away that entities can see.
      # Set this to zero to disable the line of sight restriction.
      VisionRange: 10.0
      # How wide of an angle that entities can see.
      VisionAngle: 70.0
      # The number of combo points to generate when a stealth attack is successful.
      ComboPointsGenerated: 0
    DeadlyPunch:
      Enabled: false
      # Cooldown in milliseconds.
      Cooldown: 1500
      Description: "Swing at a target and use up all combo points to deal extra damage."
      # How much damage the attack deals at full combo points. 1 damage = 0.5 hearts.
      MaxDamage: 8
    Lunge:
      Enabled: true
      # Cooldown in milliseconds.
      Cooldown: 6000
      Description: "Left-click to lunge forward."
      # Whether or not the particles are displayed while Lunge is active.
      DisplayParticles: true
      # The launch angle in degrees.
      Angle: 12.0
      # The velocity in blocks per second.
      Speed: 50.0
      # How many milliseconds it takes to cycle through all the colors in a rainbow lunge.
      # Enable rainbow Lunge with Chissentials.Lunge.Rainbow permission.
      RainbowCycleDuration: 600
