Chi:
  FlyingKick:
    Enabled: true
    # Cooldown in milliseconds.
    Cooldown: 16000
    # Number of blocks per second.
    Speed: 20.0
    # Maximum amount of time the movement state can last.
    Duration: 2000
    # How large the explosion at the end of the movement state is.
    # It should be pretty small because the particles are rendered in 3 waves.
    ExplosionRadius: 3.5
    # How long the caster has to hit the ground before the explosion is cancelled.
    GroundWaitTime: 1000
    # Amount of damage the explosion does. 1 damage = 0.5 hearts.
    Damage: 3
  Karma:
    Enabled: true
    # Cooldown in milliseconds.
    Cooldown: 40000
    # How many blocks away the target can be.
    Range: 30.0
    # How long Karma lasts with 0 combo points in milliseconsd.
    # If BaseDuration is higher than MaxDuration, Karma won't use any combo points and will default to BaseDuration.
    BaseDuration: 3000
    # How long Karma lasts with full combo points in milliseconds.
    MaxDuration: 6000
  KickPunch:
    Enabled: true
    # Cooldown in milliseconds.
    Cooldown: 1500
    # Amount of damage done. 1 damage = 0.5 hearts.
    Damage: 2
    ComboPointsGenerated: 2
  LegSweep:
    Enabled: true
    # Cooldown in milliseconds.
    Cooldown: 12000
    # How long the stun lasts in milliseconds.
    StunDuration: 1000
    # How long it takes to do a full sweep in milliseconds.
    SweepDuration: 500
    # The length of the sweep in blocks.
    SweepRadius: 3.0
  Ambush:
    Enabled: true
    # Cooldown in milliseconds.
    Cooldown: 12000
    # How much damage the attack from stealth deals. 1 damage = 0.5 hearts.
    Damage: 6
    # How long the invisibility lasts in milliseconds.
    StealthDuration: 6000
    # Whether or not being in stealth displays particles on movement.
    DisplayStealthParticles: true
    # How many blocks away the chi blocker must be from entities to use Ambush.
    NearbyRange: 10.0
